### PR TITLE
Kimpanel-IBus and Emojier packages and not enforce Fedora's LNF

### PR DESCRIPTION
**Pull request by christiantosta**
### 98fd5ff: split Kimpanel-IBus and Emojier packages
- fix: The emojier application was installed by the package but shows no glimpses (bugzilla #1855926)
- enhancement: split emojier sub-package (some corporative users can't want it on menu at all)
- enhancement: split Kimpanel IBus back-end sub-package (it's unnecessary for occidental languages)

### fb4f728:  do not hard-enforce use of Fedora's LookAndFeel
- enhancement: Enforcing Fedora artwork is not a friendly with derivative work and hurts collaborative philosophy. So we are
modified the dependencies in a way that not prohibit derivative works nor get rid of Fedora's work.

### CODE REVIEW

**Comment by ZaWertun** [comment]
I'll merge it after updating KDE Gear to 22.08.0, I'm working on update just now.

One thing - splitting `plasma-desktop` package to 2 could break compatibility with official Fedora packages, we need to test it.
I'll build your changes in separate copr first (`kde-test`), if all will be ok - I'll merge it to main branch & build packages in `kde` repo.

**Comment by ZaWertun** [comment]
I've added `plasma-desktop-emojier` as recommended package to `plasma-desktop`.
https://github.com/ZaWertun/fedora-copr-kde5/commit/7536649911445c1f47a37c5f3123286643dc4400

Builds:
1. https://copr.fedorainfracloud.org/coprs/zawertun/kde-test/build/4751332/
2. https://copr.fedorainfracloud.org/coprs/zawertun/kde-test/build/4751333/

**Comment by christiantosta** [comment]
Thank you.

Em sáb, 20 de ago de 2022 07:06, Yaroslav Sidlovsky <
***@***.***> escreveu:

**Comment by ZaWertun** [comment]
Builds:
- https://copr.fedorainfracloud.org/coprs/build/4757038
- https://copr.fedorainfracloud.org/coprs/build/4757039

**Pull request merged**
